# Generated by Django 2.1.4 on 2019-05-18 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='tilte',
            new_name='title',
        ),
    ]
